steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.9'
  inputs:
    versionSpec: '3.9'

- task: AzureCLI@2
  displayName: Install Job Requirements
  inputs:
    azureSubscription: $(AZURE_RM_SVC_CONNECTION)
    scriptType: bash
    scriptLocation: inlineScript
    workingDirectory: $(System.DefaultWorkingDirectory)
    inlineScript: |
      set -e # fail on error

      python -m pip install --upgrade pip
      python -m pip install -r .azure-pipelines/requirements/execute_job_requirements.txt
      python -m pip install promptflow==1.4.0 promptflow-tools promptflow-sdk jinja2 promptflow[azure]==1.4.0 openai promptflow-sdk[builtins] --extra-index-url https://azuremlsdktestpypi.azureedge.net/promptflow/

      az version


